apiVersion: v1
name: nginx-deployment-cd
description: Install Nginx deployment manifests
keywords:
- nginx 
version: 1.0.0
maintainers:
- name: anp
  email: anp@anp.com
dependencies:
- name: servicelb
  version: 1.0.0
  condition: servicelb.enabled, global.servicelb.enabled
- name: serviceClusterIP
  version: 1.0.0
  condition: serviceClusterIP.enabled, global.serviceClusterIP.enabled

