namespace:
  name: demo
 
service:
  port: 8111
  type: ClusterIP

image:
  repository: nginx 
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 256Mi

configmap:
  data: "version: alpine"
  
servicelb:
  enabled: false
  namespace:
    name: demo
  service:
    lbport: 8112
