namespace:
  name: nginx-prod 

image:
  repository: nginx 
  tag: 1.17.0
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 70m
    memory: 256Mi

configmap:
  data: "version: 1.17.0"
  
servicelb:
  enabled: true
  namespace:
    name: nginx-prod
  service:
    lbport: 8114

serviceClusterIP:
  enabled: false
  namespace:
    name: nginx-prod
  service:
    port: 8111
