apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine-cd-lb
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - name: http
    port: {{ .Values.service.lbport }} 
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    tag: alpine
  sessionAffinity: None
  type: LoadBalancer
