apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-helloworld-cd-lb
  name: python-helloworld-cd-lb
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - name: http
    port: 9092
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-helloworld-cd
  sessionAffinity: None
  type: LoadBalancer
