name: ci

on: [push]

jobs:
  build-test-package:
    runs-on: [linux/amd64,linux/arm64]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      -
        name: Check puyhon version
        run: echo $(python3 --version)
      -
        name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      -
        name: Run and test the Flask App
        run: |
          nohup flask run > flask.log 2>&1 &
          pytest
          kill -9 `lsof -i:5000 -t`
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_INTEGRATION_UNAME }}
          password: ${{ secrets.DH_INTEGRATION_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: anup1997/python-helloworld:v1.0.1
